package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmCodp generated by hbm2java
 */
public class CctmCodp  implements java.io.Serializable {


     private CctmCodpId id;
     private String nomCodp;
     private int idEsta;
     private int idTipo;
     private String usrCrea;
     private Date fchCrea;
     private Set cctmDires = new HashSet(0);

    public CctmCodp() {
    }

	
    public CctmCodp(CctmCodpId id, int idEsta, int idTipo, String usrCrea, Date fchCrea) {
        this.id = id;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmCodp(CctmCodpId id, String nomCodp, int idEsta, int idTipo, String usrCrea, Date fchCrea, Set cctmDires) {
       this.id = id;
       this.nomCodp = nomCodp;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.cctmDires = cctmDires;
    }
   
    public CctmCodpId getId() {
        return this.id;
    }
    
    public void setId(CctmCodpId id) {
        this.id = id;
    }
    public String getNomCodp() {
        return this.nomCodp;
    }
    
    public void setNomCodp(String nomCodp) {
        this.nomCodp = nomCodp;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Set getCctmDires() {
        return this.cctmDires;
    }
    
    public void setCctmDires(Set cctmDires) {
        this.cctmDires = cctmDires;
    }




}


