package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1



/**
 * CctmCiudId generated by hbm2java
 */
public class CctmCiudId  implements java.io.Serializable {


     private int idCiud;
     private int idEstd;

    public CctmCiudId() {
    }

    public CctmCiudId(int idCiud, int idEstd) {
       this.idCiud = idCiud;
       this.idEstd = idEstd;
    }
   
    public int getIdCiud() {
        return this.idCiud;
    }
    
    public void setIdCiud(int idCiud) {
        this.idCiud = idCiud;
    }
    public int getIdEstd() {
        return this.idEstd;
    }
    
    public void setIdEstd(int idEstd) {
        this.idEstd = idEstd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CctmCiudId) ) return false;
		 CctmCiudId castOther = ( CctmCiudId ) other; 
         
		 return (this.getIdCiud()==castOther.getIdCiud())
 && (this.getIdEstd()==castOther.getIdEstd());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCiud();
         result = 37 * result + this.getIdEstd();
         return result;
   }   


}


