package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmArpo generated by hbm2java
 */
public class CctmArpo  implements java.io.Serializable {


     private int idArpo;
     private String nameArpo;
     private int valeArpo;
     private int colrArpo;
     private int idEsta;
     private int idTipo;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Integer idConSis;
     private Set sfalConfs = new HashSet(0);

    public CctmArpo() {
    }

	
    public CctmArpo(int idArpo, String nameArpo, int valeArpo, int colrArpo, int idEsta, int idTipo, String usrCrea, Date fchCrea) {
        this.idArpo = idArpo;
        this.nameArpo = nameArpo;
        this.valeArpo = valeArpo;
        this.colrArpo = colrArpo;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmArpo(int idArpo, String nameArpo, int valeArpo, int colrArpo, int idEsta, int idTipo, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Integer idConSis, Set sfalConfs) {
       this.idArpo = idArpo;
       this.nameArpo = nameArpo;
       this.valeArpo = valeArpo;
       this.colrArpo = colrArpo;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idConSis = idConSis;
       this.sfalConfs = sfalConfs;
    }
   
    public int getIdArpo() {
        return this.idArpo;
    }
    
    public void setIdArpo(int idArpo) {
        this.idArpo = idArpo;
    }
    public String getNameArpo() {
        return this.nameArpo;
    }
    
    public void setNameArpo(String nameArpo) {
        this.nameArpo = nameArpo;
    }
    public int getValeArpo() {
        return this.valeArpo;
    }
    
    public void setValeArpo(int valeArpo) {
        this.valeArpo = valeArpo;
    }
    public int getColrArpo() {
        return this.colrArpo;
    }
    
    public void setColrArpo(int colrArpo) {
        this.colrArpo = colrArpo;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }
    public Set getSfalConfs() {
        return this.sfalConfs;
    }
    
    public void setSfalConfs(Set sfalConfs) {
        this.sfalConfs = sfalConfs;
    }




}


