package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmEstd generated by hbm2java
 */
public class CctmEstd  implements java.io.Serializable {


     private int idEstd;
     private String nomEstd;
     private int idEsta;
     private int idTipo;
     private String usrCrea;
     private Date fchCrea;
     private Set cctmDires = new HashSet(0);

    public CctmEstd() {
    }

	
    public CctmEstd(int idEstd, int idEsta, int idTipo, String usrCrea, Date fchCrea) {
        this.idEstd = idEstd;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmEstd(int idEstd, String nomEstd, int idEsta, int idTipo, String usrCrea, Date fchCrea, Set cctmDires) {
       this.idEstd = idEstd;
       this.nomEstd = nomEstd;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.cctmDires = cctmDires;
    }
   
    public int getIdEstd() {
        return this.idEstd;
    }
    
    public void setIdEstd(int idEstd) {
        this.idEstd = idEstd;
    }
    public String getNomEstd() {
        return this.nomEstd;
    }
    
    public void setNomEstd(String nomEstd) {
        this.nomEstd = nomEstd;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Set getCctmDires() {
        return this.cctmDires;
    }
    
    public void setCctmDires(Set cctmDires) {
        this.cctmDires = cctmDires;
    }




}


