package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SfcrVehiCond generated by hbm2java
 */
public class SfcrVehiCond  implements java.io.Serializable {


     private int idVehiCond;
     private SfemCond sfemCond;
     private SfvhVehi sfvhVehi;
     private Date fchCrea;
     private Boolean stat;
     private Set sfpfItins = new HashSet(0);

    public SfcrVehiCond() {
    }

	
    public SfcrVehiCond(int idVehiCond) {
        this.idVehiCond = idVehiCond;
    }
    public SfcrVehiCond(int idVehiCond, SfemCond sfemCond, SfvhVehi sfvhVehi, Date fchCrea, Boolean stat, Set sfpfItins) {
       this.idVehiCond = idVehiCond;
       this.sfemCond = sfemCond;
       this.sfvhVehi = sfvhVehi;
       this.fchCrea = fchCrea;
       this.stat = stat;
       this.sfpfItins = sfpfItins;
    }
   
    public int getIdVehiCond() {
        return this.idVehiCond;
    }
    
    public void setIdVehiCond(int idVehiCond) {
        this.idVehiCond = idVehiCond;
    }
    public SfemCond getSfemCond() {
        return this.sfemCond;
    }
    
    public void setSfemCond(SfemCond sfemCond) {
        this.sfemCond = sfemCond;
    }
    public SfvhVehi getSfvhVehi() {
        return this.sfvhVehi;
    }
    
    public void setSfvhVehi(SfvhVehi sfvhVehi) {
        this.sfvhVehi = sfvhVehi;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Boolean getStat() {
        return this.stat;
    }
    
    public void setStat(Boolean stat) {
        this.stat = stat;
    }
    public Set getSfpfItins() {
        return this.sfpfItins;
    }
    
    public void setSfpfItins(Set sfpfItins) {
        this.sfpfItins = sfpfItins;
    }




}


