package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SfdtDiti generated by hbm2java
 */
public class SfdtDiti  implements java.io.Serializable {


     private int idDiti;
     private SfesEst sfesEstByIdEsto;
     private SfesEst sfesEstByIdEstd;
     private SfpfItin sfpfItin;
     private Date horEsal;
     private Date horElle;
     private Date horaReal;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private int idEsta;
     private int idTipo;

    public SfdtDiti() {
    }

	
    public SfdtDiti(int idDiti, SfesEst sfesEstByIdEsto, SfesEst sfesEstByIdEstd, SfpfItin sfpfItin, Date horEsal, Date horElle, Date horaReal, String usrCrea, Date fchCrea, int idEsta, int idTipo) {
        this.idDiti = idDiti;
        this.sfesEstByIdEsto = sfesEstByIdEsto;
        this.sfesEstByIdEstd = sfesEstByIdEstd;
        this.sfpfItin = sfpfItin;
        this.horEsal = horEsal;
        this.horElle = horElle;
        this.horaReal = horaReal;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
    }
    public SfdtDiti(int idDiti, SfesEst sfesEstByIdEsto, SfesEst sfesEstByIdEstd, SfpfItin sfpfItin, Date horEsal, Date horElle, Date horaReal, String usrCrea, Date fchCrea, String usrModi, Date fchModi, int idEsta, int idTipo) {
       this.idDiti = idDiti;
       this.sfesEstByIdEsto = sfesEstByIdEsto;
       this.sfesEstByIdEstd = sfesEstByIdEstd;
       this.sfpfItin = sfpfItin;
       this.horEsal = horEsal;
       this.horElle = horElle;
       this.horaReal = horaReal;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
    }
   
    public int getIdDiti() {
        return this.idDiti;
    }
    
    public void setIdDiti(int idDiti) {
        this.idDiti = idDiti;
    }
    public SfesEst getSfesEstByIdEsto() {
        return this.sfesEstByIdEsto;
    }
    
    public void setSfesEstByIdEsto(SfesEst sfesEstByIdEsto) {
        this.sfesEstByIdEsto = sfesEstByIdEsto;
    }
    public SfesEst getSfesEstByIdEstd() {
        return this.sfesEstByIdEstd;
    }
    
    public void setSfesEstByIdEstd(SfesEst sfesEstByIdEstd) {
        this.sfesEstByIdEstd = sfesEstByIdEstd;
    }
    public SfpfItin getSfpfItin() {
        return this.sfpfItin;
    }
    
    public void setSfpfItin(SfpfItin sfpfItin) {
        this.sfpfItin = sfpfItin;
    }
    public Date getHorEsal() {
        return this.horEsal;
    }
    
    public void setHorEsal(Date horEsal) {
        this.horEsal = horEsal;
    }
    public Date getHorElle() {
        return this.horElle;
    }
    
    public void setHorElle(Date horElle) {
        this.horElle = horElle;
    }
    public Date getHoraReal() {
        return this.horaReal;
    }
    
    public void setHoraReal(Date horaReal) {
        this.horaReal = horaReal;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }




}


