package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SfemCond generated by hbm2java
 */
public class SfemCond  implements java.io.Serializable {


     private int idEmpCond;
     private SfpcCata sfpcCata;
     private Integer numLic;
     private Date fchVen;
     private Integer idTipoLic;
     private String userCond;
     private String passCond;
     private Set sfcrVehiConds = new HashSet(0);

    public SfemCond() {
    }

	
    public SfemCond(int idEmpCond) {
        this.idEmpCond = idEmpCond;
    }
    public SfemCond(int idEmpCond, SfpcCata sfpcCata, Integer numLic, Date fchVen, Integer idTipoLic, String userCond, String passCond, Set sfcrVehiConds) {
       this.idEmpCond = idEmpCond;
       this.sfpcCata = sfpcCata;
       this.numLic = numLic;
       this.fchVen = fchVen;
       this.idTipoLic = idTipoLic;
       this.userCond = userCond;
       this.passCond = passCond;
       this.sfcrVehiConds = sfcrVehiConds;
    }
   
    public int getIdEmpCond() {
        return this.idEmpCond;
    }
    
    public void setIdEmpCond(int idEmpCond) {
        this.idEmpCond = idEmpCond;
    }
    public SfpcCata getSfpcCata() {
        return this.sfpcCata;
    }
    
    public void setSfpcCata(SfpcCata sfpcCata) {
        this.sfpcCata = sfpcCata;
    }
    public Integer getNumLic() {
        return this.numLic;
    }
    
    public void setNumLic(Integer numLic) {
        this.numLic = numLic;
    }
    public Date getFchVen() {
        return this.fchVen;
    }
    
    public void setFchVen(Date fchVen) {
        this.fchVen = fchVen;
    }
    public Integer getIdTipoLic() {
        return this.idTipoLic;
    }
    
    public void setIdTipoLic(Integer idTipoLic) {
        this.idTipoLic = idTipoLic;
    }
    public String getUserCond() {
        return this.userCond;
    }
    
    public void setUserCond(String userCond) {
        this.userCond = userCond;
    }
    public String getPassCond() {
        return this.passCond;
    }
    
    public void setPassCond(String passCond) {
        this.passCond = passCond;
    }
    public Set getSfcrVehiConds() {
        return this.sfcrVehiConds;
    }
    
    public void setSfcrVehiConds(Set sfcrVehiConds) {
        this.sfcrVehiConds = sfcrVehiConds;
    }




}


