package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SfgfHoseFlot generated by hbm2java
 */
public class SfgfHoseFlot  implements java.io.Serializable {


     private int idHoraServ;
     private SfpcCata sfpcCata;
     private Date horaInic;
     private Date horaFin;
     private Date fchOper;
     private Integer diaOper;
     private String descServ;

    public SfgfHoseFlot() {
    }

	
    public SfgfHoseFlot(int idHoraServ) {
        this.idHoraServ = idHoraServ;
    }
    public SfgfHoseFlot(int idHoraServ, SfpcCata sfpcCata, Date horaInic, Date horaFin, Date fchOper, Integer diaOper, String descServ) {
       this.idHoraServ = idHoraServ;
       this.sfpcCata = sfpcCata;
       this.horaInic = horaInic;
       this.horaFin = horaFin;
       this.fchOper = fchOper;
       this.diaOper = diaOper;
       this.descServ = descServ;
    }
   
    public int getIdHoraServ() {
        return this.idHoraServ;
    }
    
    public void setIdHoraServ(int idHoraServ) {
        this.idHoraServ = idHoraServ;
    }
    public SfpcCata getSfpcCata() {
        return this.sfpcCata;
    }
    
    public void setSfpcCata(SfpcCata sfpcCata) {
        this.sfpcCata = sfpcCata;
    }
    public Date getHoraInic() {
        return this.horaInic;
    }
    
    public void setHoraInic(Date horaInic) {
        this.horaInic = horaInic;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Date getFchOper() {
        return this.fchOper;
    }
    
    public void setFchOper(Date fchOper) {
        this.fchOper = fchOper;
    }
    public Integer getDiaOper() {
        return this.diaOper;
    }
    
    public void setDiaOper(Integer diaOper) {
        this.diaOper = diaOper;
    }
    public String getDescServ() {
        return this.descServ;
    }
    
    public void setDescServ(String descServ) {
        this.descServ = descServ;
    }




}


