package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SflnLin generated by hbm2java
 */
public class SflnLin  implements java.io.Serializable {


     private int idLin;
     private String nom;
     private String descLin;
     private double distEst;
     private int idConSis;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private int idEsta;
     private int idTipo;
     private int idTipoLin;
     private Date tiemEst;
     private Set sfruRutas = new HashSet(0);
     private Set sfmoTipus = new HashSet(0);

    public SflnLin() {
    }

	
    public SflnLin(int idLin, String nom, String descLin, double distEst, int idConSis, String usrCrea, Date fchCrea, int idEsta, int idTipo, int idTipoLin, Date tiemEst) {
        this.idLin = idLin;
        this.nom = nom;
        this.descLin = descLin;
        this.distEst = distEst;
        this.idConSis = idConSis;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.idTipoLin = idTipoLin;
        this.tiemEst = tiemEst;
    }
    public SflnLin(int idLin, String nom, String descLin, double distEst, int idConSis, String usrCrea, Date fchCrea, String usrModi, Date fchModi, int idEsta, int idTipo, int idTipoLin, Date tiemEst, Set sfruRutas, Set sfmoTipus) {
       this.idLin = idLin;
       this.nom = nom;
       this.descLin = descLin;
       this.distEst = distEst;
       this.idConSis = idConSis;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.idTipoLin = idTipoLin;
       this.tiemEst = tiemEst;
       this.sfruRutas = sfruRutas;
       this.sfmoTipus = sfmoTipus;
    }
   
    public int getIdLin() {
        return this.idLin;
    }
    
    public void setIdLin(int idLin) {
        this.idLin = idLin;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescLin() {
        return this.descLin;
    }
    
    public void setDescLin(String descLin) {
        this.descLin = descLin;
    }
    public double getDistEst() {
        return this.distEst;
    }
    
    public void setDistEst(double distEst) {
        this.distEst = distEst;
    }
    public int getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(int idConSis) {
        this.idConSis = idConSis;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public int getIdTipoLin() {
        return this.idTipoLin;
    }
    
    public void setIdTipoLin(int idTipoLin) {
        this.idTipoLin = idTipoLin;
    }
    public Date getTiemEst() {
        return this.tiemEst;
    }
    
    public void setTiemEst(Date tiemEst) {
        this.tiemEst = tiemEst;
    }
    public Set getSfruRutas() {
        return this.sfruRutas;
    }
    
    public void setSfruRutas(Set sfruRutas) {
        this.sfruRutas = sfruRutas;
    }
    public Set getSfmoTipus() {
        return this.sfmoTipus;
    }
    
    public void setSfmoTipus(Set sfmoTipus) {
        this.sfmoTipus = sfmoTipus;
    }




}


