package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SfopEquiAlar generated by hbm2java
 */
public class SfopEquiAlar  implements java.io.Serializable {


     private int idOpeqAlar;
     private SbctAlar sbctAlar;
     private SfvhVehi sfvhVehi;
     private Date fchInic;
     private Date fchFin;
     private Character estaEqui;
     private Double latiAlar;
     private Double lontAlar;
     private Integer idEst;
     private Integer statAlar;
     private Double tramGps;
     private Integer estaAnti;
     private String descOpeqAlar;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private int idEsta;
     private int idTipo;

    public SfopEquiAlar() {
    }

	
    public SfopEquiAlar(int idOpeqAlar, String usrCrea, Date fchCrea, int idEsta, int idTipo) {
        this.idOpeqAlar = idOpeqAlar;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
    }
    public SfopEquiAlar(int idOpeqAlar, SbctAlar sbctAlar, SfvhVehi sfvhVehi, Date fchInic, Date fchFin, Character estaEqui, Double latiAlar, Double lontAlar, Integer idEst, Integer statAlar, Double tramGps, Integer estaAnti, String descOpeqAlar, String usrCrea, Date fchCrea, String usrModi, Date fchModi, int idEsta, int idTipo) {
       this.idOpeqAlar = idOpeqAlar;
       this.sbctAlar = sbctAlar;
       this.sfvhVehi = sfvhVehi;
       this.fchInic = fchInic;
       this.fchFin = fchFin;
       this.estaEqui = estaEqui;
       this.latiAlar = latiAlar;
       this.lontAlar = lontAlar;
       this.idEst = idEst;
       this.statAlar = statAlar;
       this.tramGps = tramGps;
       this.estaAnti = estaAnti;
       this.descOpeqAlar = descOpeqAlar;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
    }
   
    public int getIdOpeqAlar() {
        return this.idOpeqAlar;
    }
    
    public void setIdOpeqAlar(int idOpeqAlar) {
        this.idOpeqAlar = idOpeqAlar;
    }
    public SbctAlar getSbctAlar() {
        return this.sbctAlar;
    }
    
    public void setSbctAlar(SbctAlar sbctAlar) {
        this.sbctAlar = sbctAlar;
    }
    public SfvhVehi getSfvhVehi() {
        return this.sfvhVehi;
    }
    
    public void setSfvhVehi(SfvhVehi sfvhVehi) {
        this.sfvhVehi = sfvhVehi;
    }
    public Date getFchInic() {
        return this.fchInic;
    }
    
    public void setFchInic(Date fchInic) {
        this.fchInic = fchInic;
    }
    public Date getFchFin() {
        return this.fchFin;
    }
    
    public void setFchFin(Date fchFin) {
        this.fchFin = fchFin;
    }
    public Character getEstaEqui() {
        return this.estaEqui;
    }
    
    public void setEstaEqui(Character estaEqui) {
        this.estaEqui = estaEqui;
    }
    public Double getLatiAlar() {
        return this.latiAlar;
    }
    
    public void setLatiAlar(Double latiAlar) {
        this.latiAlar = latiAlar;
    }
    public Double getLontAlar() {
        return this.lontAlar;
    }
    
    public void setLontAlar(Double lontAlar) {
        this.lontAlar = lontAlar;
    }
    public Integer getIdEst() {
        return this.idEst;
    }
    
    public void setIdEst(Integer idEst) {
        this.idEst = idEst;
    }
    public Integer getStatAlar() {
        return this.statAlar;
    }
    
    public void setStatAlar(Integer statAlar) {
        this.statAlar = statAlar;
    }
    public Double getTramGps() {
        return this.tramGps;
    }
    
    public void setTramGps(Double tramGps) {
        this.tramGps = tramGps;
    }
    public Integer getEstaAnti() {
        return this.estaAnti;
    }
    
    public void setEstaAnti(Integer estaAnti) {
        this.estaAnti = estaAnti;
    }
    public String getDescOpeqAlar() {
        return this.descOpeqAlar;
    }
    
    public void setDescOpeqAlar(String descOpeqAlar) {
        this.descOpeqAlar = descOpeqAlar;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }




}


