package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SfpcCata generated by hbm2java
 */
public class SfpcCata  implements java.io.Serializable {


     private int idCata;
     private String codCata;
     private String codCort;
     private String desCort;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private int idEsta;
     private Integer idTipo;
     private Set sfgfHoseFlots = new HashSet(0);
     private Set sfgfHoseFlots_1 = new HashSet(0);
     private Set sfemConds = new HashSet(0);

    public SfpcCata() {
    }

	
    public SfpcCata(int idCata, String codCata, String codCort, String desCort, String usrCrea, Date fchCrea, int idEsta) {
        this.idCata = idCata;
        this.codCata = codCata;
        this.codCort = codCort;
        this.desCort = desCort;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idEsta = idEsta;
    }
    public SfpcCata(int idCata, String codCata, String codCort, String desCort, String usrCrea, Date fchCrea, String usrModi, Date fchModi, int idEsta, Integer idTipo, Set sfgfHoseFlots, Set sfgfHoseFlots_1, Set sfemConds) {
       this.idCata = idCata;
       this.codCata = codCata;
       this.codCort = codCort;
       this.desCort = desCort;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.sfgfHoseFlots = sfgfHoseFlots;
       this.sfgfHoseFlots_1 = sfgfHoseFlots_1;
       this.sfemConds = sfemConds;
    }
   
    public int getIdCata() {
        return this.idCata;
    }
    
    public void setIdCata(int idCata) {
        this.idCata = idCata;
    }
    public String getCodCata() {
        return this.codCata;
    }
    
    public void setCodCata(String codCata) {
        this.codCata = codCata;
    }
    public String getCodCort() {
        return this.codCort;
    }
    
    public void setCodCort(String codCort) {
        this.codCort = codCort;
    }
    public String getDesCort() {
        return this.desCort;
    }
    
    public void setDesCort(String desCort) {
        this.desCort = desCort;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public Set getSfgfHoseFlots() {
        return this.sfgfHoseFlots;
    }
    
    public void setSfgfHoseFlots(Set sfgfHoseFlots) {
        this.sfgfHoseFlots = sfgfHoseFlots;
    }
    public Set getSfgfHoseFlots_1() {
        return this.sfgfHoseFlots_1;
    }
    
    public void setSfgfHoseFlots_1(Set sfgfHoseFlots_1) {
        this.sfgfHoseFlots_1 = sfgfHoseFlots_1;
    }
    public Set getSfemConds() {
        return this.sfemConds;
    }
    
    public void setSfemConds(Set sfemConds) {
        this.sfemConds = sfemConds;
    }




}


