package com.mx.teknei.pc.lib.entities;
// Generated 1/10/2015 08:51:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SfruCrut generated by hbm2java
 */
public class SfruCrut  implements java.io.Serializable {


     private int idDrut;
     private SfesEst sfesEstByIdEstOrig;
     private SfesEst sfesEstByIdEstDest;
     private SfruRuta sfruRuta;
     private Double distDrut;
     private Integer tipoDire;
     private Date tiemDrut;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private int idEsta;
     private Integer idTipo;
     private Integer idConSis;

    public SfruCrut() {
    }

	
    public SfruCrut(int idDrut, String usrCrea, Date fchCrea, int idEsta) {
        this.idDrut = idDrut;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idEsta = idEsta;
    }
    public SfruCrut(int idDrut, SfesEst sfesEstByIdEstOrig, SfesEst sfesEstByIdEstDest, SfruRuta sfruRuta, Double distDrut, Integer tipoDire, Date tiemDrut, String usrCrea, Date fchCrea, String usrModi, Date fchModi, int idEsta, Integer idTipo, Integer idConSis) {
       this.idDrut = idDrut;
       this.sfesEstByIdEstOrig = sfesEstByIdEstOrig;
       this.sfesEstByIdEstDest = sfesEstByIdEstDest;
       this.sfruRuta = sfruRuta;
       this.distDrut = distDrut;
       this.tipoDire = tipoDire;
       this.tiemDrut = tiemDrut;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.idConSis = idConSis;
    }
   
    public int getIdDrut() {
        return this.idDrut;
    }
    
    public void setIdDrut(int idDrut) {
        this.idDrut = idDrut;
    }
    public SfesEst getSfesEstByIdEstOrig() {
        return this.sfesEstByIdEstOrig;
    }
    
    public void setSfesEstByIdEstOrig(SfesEst sfesEstByIdEstOrig) {
        this.sfesEstByIdEstOrig = sfesEstByIdEstOrig;
    }
    public SfesEst getSfesEstByIdEstDest() {
        return this.sfesEstByIdEstDest;
    }
    
    public void setSfesEstByIdEstDest(SfesEst sfesEstByIdEstDest) {
        this.sfesEstByIdEstDest = sfesEstByIdEstDest;
    }
    public SfruRuta getSfruRuta() {
        return this.sfruRuta;
    }
    
    public void setSfruRuta(SfruRuta sfruRuta) {
        this.sfruRuta = sfruRuta;
    }
    public Double getDistDrut() {
        return this.distDrut;
    }
    
    public void setDistDrut(Double distDrut) {
        this.distDrut = distDrut;
    }
    public Integer getTipoDire() {
        return this.tipoDire;
    }
    
    public void setTipoDire(Integer tipoDire) {
        this.tipoDire = tipoDire;
    }
    public Date getTiemDrut() {
        return this.tiemDrut;
    }
    
    public void setTiemDrut(Date tiemDrut) {
        this.tiemDrut = tiemDrut;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }




}


